oxygen_helmet:
  material: BLUE_STAINED_GLASS
  displayName: "&bГермошлем"
  lore:
    - " "
    - "&f Защищает от радиации"
    - "&f На всех &bпланетах!"
    - " "
armor_toughness:
  IRON_HELMET: 1
  IRON_CHESTPLATE: 1
  IRON_LEGGINGS: 1
  IRON_BOOTS: 1
  DIAMOND_HELMET: 2
  DIAMOND_LEGGINGS: 2
  DIAMOND_CHESTPLATE: 2
  DIAMOND_BOOTS: 2
  NETHERITE_HELMET: 3
  NETHERITE_CHESTPLATE: 3
  NETHERITE_LEGGINGS: 3
  NETHERITE_BOOTS: 3
storages:
  refreshTime: 60
  holograms:
    isOpened:
      height: 2.4
      lines: []
    isClosed:
      height: 2.4
      lines: [ ]
    inTimer:
      updatable: true
      height: 2.4
      lines: [ ]
messages:
  editMenu_title: "&0Редактирование"
  noPermission: []
  reload: []
  unknownPlayer: []
  setStorage: []
  updateStorage: []
  storageIsClaimed: []
  storageIsOpened: []
  addItem: []
  giveOxyHelmet: "[player]"