name: SatePlanet
version: '1.0.9'
main: org.satellite.dev.progiple.sateplanet.SatePlanet
api-version: '1.16'
authors: [ProGiple]
depend:
  - LunaSpring
  - NBTAPI
  - DecentHolograms
  - SateCustomItems
commands:
  sateplanet:
    usage: /sateplanet reload/give <player>/storage <set, update>/planet <player>
    aliases:
      - sp
      - satep
      - sateplanets
      - planet
      - plantes
      - splanet
      - splanets
permissions:
  sateplanet.planet:
    default: true
  sateplanet.admin:
    default: op
  sateplanet.bypass.oxygen:
    default: false
  sateplanet.bypass.gravitation:
    default: false
  sateplanet.bypass.teleport:
    default: false